2018-01-03 16:02:57 TRACE - getAccount() Invoked
2018-01-03 16:02:57 DEBUG - checking the aid against map key
2018-01-03 16:02:57 ERROR - Id not found
com.sapient.exception.IdExceptin: Id not found
	at com.sapient.dao.DaoImpl.getAccount(DaoImpl.java:32)
	at com.sapient.service.SerImpl.transfrFund(SerImpl.java:40)
	at com.sapient.client.TransferClient.main(TransferClient.java:20)
2018-01-03 16:02:57 INFO - transfer the amount RS.5000 from accId 1003 to 1002
2018-01-03 16:02:57 TRACE - transferfund()  invoked in service
2018-01-03 16:02:57 TRACE - getAccount() Invoked
2018-01-03 16:02:57 DEBUG - checking the aid against map key
2018-01-03 16:02:57 ERROR - Id not found
com.sapient.exception.IdExceptin: Id not found
	at com.sapient.dao.DaoImpl.getAccount(DaoImpl.java:32)
	at com.sapient.service.SerImpl.transfrFund(SerImpl.java:38)
	at com.sapient.client.TransferClient.main(TransferClient.java:28)
2018-01-03 16:02:57 INFO - transfer the amount RS.5000 from accId 1003 to 1002
2018-01-03 16:02:57 TRACE - transferfund()  invoked in service
2018-01-03 16:02:57 TRACE - getAccount() Invoked
2018-01-03 16:02:57 DEBUG - checking the aid against map key
2018-01-03 16:02:57 ERROR - Id not found
com.sapient.exception.IdExceptin: Id not found
	at com.sapient.dao.DaoImpl.getAccount(DaoImpl.java:32)
	at com.sapient.service.SerImpl.transfrFund(SerImpl.java:38)
	at com.sapient.client.TransferClient.main(TransferClient.java:36)
2018-01-03 16:03:12 TRACE - getAccount() Invoked
2018-01-03 16:03:12 DEBUG - checking the aid against map key
2018-01-03 16:03:12 ERROR - Id not found
com.sapient.exception.IdExceptin: Id not found
	at com.sapient.dao.DaoImpl.getAccount(DaoImpl.java:32)
	at com.sapient.service.SerImpl.transfrFund(SerImpl.java:40)
	at com.sapient.client.TransferClient.main(TransferClient.java:20)
2018-01-03 16:03:12 INFO - transfer the amount RS.5000 from accId 1003 to 1002
2018-01-03 16:03:12 TRACE - transferfund()  invoked in service
2018-01-03 16:03:12 TRACE - getAccount() Invoked
2018-01-03 16:03:12 DEBUG - checking the aid against map key
2018-01-03 16:03:12 ERROR - Id not found
com.sapient.exception.IdExceptin: Id not found
	at com.sapient.dao.DaoImpl.getAccount(DaoImpl.java:32)
	at com.sapient.service.SerImpl.transfrFund(SerImpl.java:38)
	at com.sapient.client.TransferClient.main(TransferClient.java:28)
2018-01-03 16:03:12 INFO - transfer the amount RS.5000 from accId 1003 to 1002
2018-01-03 16:03:12 TRACE - transferfund()  invoked in service
2018-01-03 16:03:12 TRACE - getAccount() Invoked
2018-01-03 16:03:12 DEBUG - checking the aid against map key
2018-01-03 16:03:12 ERROR - Id not found
com.sapient.exception.IdExceptin: Id not found
	at com.sapient.dao.DaoImpl.getAccount(DaoImpl.java:32)
	at com.sapient.service.SerImpl.transfrFund(SerImpl.java:38)
	at com.sapient.client.TransferClient.main(TransferClient.java:36)
2018-01-03 16:06:10 TRACE - getAccount() Invoked
2018-01-03 16:06:10 DEBUG - checking the aid against map key
2018-01-03 16:06:10 ERROR - Id not found
com.sapient.exception.IdExceptin: Id not found
	at com.sapient.dao.DaoImpl.getAccount(DaoImpl.java:32)
	at com.sapient.service.SerImpl.transfrFund(SerImpl.java:40)
	at com.sapient.client.TransferClient.main(TransferClient.java:20)
2018-01-03 16:06:10 INFO - transfer the amount RS.5000 from accId 1003 to 1002
2018-01-03 16:06:10 TRACE - transferfund()  invoked in service
2018-01-03 16:06:10 TRACE - getAccount() Invoked
2018-01-03 16:06:10 DEBUG - checking the aid against map key
2018-01-03 16:06:10 ERROR - Id not found
com.sapient.exception.IdExceptin: Id not found
	at com.sapient.dao.DaoImpl.getAccount(DaoImpl.java:32)
	at com.sapient.service.SerImpl.transfrFund(SerImpl.java:38)
	at com.sapient.client.TransferClient.main(TransferClient.java:28)
2018-01-03 16:06:10 INFO - transfer the amount RS.5000 from accId 1003 to 1002
2018-01-03 16:06:10 TRACE - transferfund()  invoked in service
2018-01-03 16:06:10 TRACE - getAccount() Invoked
2018-01-03 16:06:10 DEBUG - checking the aid against map key
2018-01-03 16:06:10 ERROR - Id not found
com.sapient.exception.IdExceptin: Id not found
	at com.sapient.dao.DaoImpl.getAccount(DaoImpl.java:32)
	at com.sapient.service.SerImpl.transfrFund(SerImpl.java:38)
	at com.sapient.client.TransferClient.main(TransferClient.java:36)
