2018-01-02 16:56:30,270 [main] TRACE  sapient - main thread start
2018-01-02 16:56:30,273 [main] TRACE  sapient - service constructure invoked
2018-01-02 16:56:30,274 [main] TRACE  sapient - static block called in dao
2018-01-02 16:56:30,274 [main] DEBUG  sapient - Has map has initialized with 3 account instance
2018-01-02 16:56:30,274 [main] TRACE  sapient - setter setDao()  invoked
2018-01-02 16:56:30,274 [main] DEBUG  sapient - Injectind dao
2018-01-02 16:56:30,275 [main] INFO   sapient - dao initialized
2018-01-02 16:56:30,275 [main] INFO   sapient - Service instance is ready with dao instance
2018-01-02 16:56:30,275 [main] DEBUG  sapient - service instance created
2018-01-02 16:56:30,275 [main] INFO   sapient - transfer the amount RS.5000 from accId 1001 to 1002
2018-01-02 16:56:30,275 [main] TRACE  sapient - transferfund()  invoked in service
2018-01-02 16:56:30,275 [main] TRACE  sapient - getAccount() Invoked
2018-01-02 16:56:30,275 [main] DEBUG  sapient - checking the aid against map key
2018-01-02 16:56:30,275 [main] INFO   sapient - account id 1001  found
2018-01-02 16:56:30,276 [main] DEBUG  sapient - from account retrieved
2018-01-02 16:56:30,276 [main] TRACE  sapient - getAccount() Invoked
2018-01-02 16:56:30,277 [main] DEBUG  sapient - checking the aid against map key
2018-01-02 16:56:30,278 [main] ERROR  sapient - Id not found
com.sapient.exception.IdExceptin: Id not found
	at com.sapient.dao.DaoImpl.getAccount(DaoImpl.java:32)
	at com.sapient.service.SerImpl.transfrFund(SerImpl.java:40)
	at com.sapient.client.TransferClient.main(TransferClient.java:20)
2018-01-02 16:56:30,278 [main] INFO   sapient - transfer the amount RS.5000 from accId 1003 to 1002
2018-01-02 16:56:30,278 [main] TRACE  sapient - transferfund()  invoked in service
2018-01-02 16:56:30,278 [main] TRACE  sapient - getAccount() Invoked
2018-01-02 16:56:30,279 [main] DEBUG  sapient - checking the aid against map key
2018-01-02 16:56:30,279 [main] ERROR  sapient - Id not found
com.sapient.exception.IdExceptin: Id not found
	at com.sapient.dao.DaoImpl.getAccount(DaoImpl.java:32)
	at com.sapient.service.SerImpl.transfrFund(SerImpl.java:38)
	at com.sapient.client.TransferClient.main(TransferClient.java:28)
2018-01-02 16:56:30,279 [main] INFO   sapient - transfer the amount RS.5000 from accId 1003 to 1002
2018-01-02 16:56:30,279 [main] TRACE  sapient - transferfund()  invoked in service
2018-01-02 16:56:30,279 [main] TRACE  sapient - getAccount() Invoked
2018-01-02 16:56:30,279 [main] DEBUG  sapient - checking the aid against map key
2018-01-02 16:56:30,279 [main] ERROR  sapient - Id not found
com.sapient.exception.IdExceptin: Id not found
	at com.sapient.dao.DaoImpl.getAccount(DaoImpl.java:32)
	at com.sapient.service.SerImpl.transfrFund(SerImpl.java:38)
	at com.sapient.client.TransferClient.main(TransferClient.java:36)
